### ISSUE TITLE
confiure publish

### ISSUE THREAD

**Issue by Fr33maan** [perak/user-roles#3]
Hello,

How could I add the createdAt filed in publication without having to modify the package ? 

Is there is any way to configure it ? 

thanks

**Comment by perak** [comment]
@l1br3 you can add somewhere in server scope:

```
Users.before.insert(function(userId, doc) {
  doc.createdAt = new Date();
});
```

**Comment by Fr33maan** [comment]
That was exactly the solution I was thinking about but unfortunately I cannot do that : 

I'm making an admin panel for an existing app and I have no control on how users are generated except admins... but i need users infos.

Why do you hide this information for admins ? 

[user-roles/server/publications/admin_users.js](https://github.com/perak/user-roles/blob/master/server/publications/admin_users.js#L2)

**Comment by perak** [comment]
@l1br3 you can create your own publication at server:

```
Meteor.publish("my_admin_users", function() {
    return Users.isAdmin(this.userId) ? Meteor.users.find({}, {fields: {profile: 1, roles: 1, emails: 1, createdAt: 1}}) : this.ready();
});
```

**Comment by Fr33maan** [comment]
Then I guess that I have to create a query called "my_admin_users" and set this query in my component ? 

Sorry I'm not familiar with meteor-kitchen yet.

**Comment by perak** [comment]
Yes, exactly.

**Comment by Fr33maan** [comment]
And its working perfectly. 

Such a pleasure to work with meteor-kitchen.

Thanks for your awesome support !
